server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomtest_db
    username: postgres
    password: "admin"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # Set db schema when app run
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql 
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app:
  jwt:
    secret: "c9f3e098a7b6d5c4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0"
